### ISSUE TITLE
Android X issue

### ISSUE THREAD

**Issue by NewITCorp** [DarkSouL11/flutter_directory_picker#1]
Hi, I got an error during compilation. 

`C:\flutter\.pub-cache\hosted\pub.dartlang.org\simple_permissions-0.1.9\android\src\main\java\com\ethras\simplepermissions\SimplePermissionsPlugin.java:9: error: cannot find symbol
import android.support.v4.app.ActivityCompat;
                             ^
  symbol:   class ActivityCompat
  location: package android.support.v4.app
C:\flutter\.pub-cache\hosted\pub.dartlang.org\simple_permissions-0.1.9\android\src\main\java\com\ethras\simplepermissions\SimplePermissionsPlugin.java:10: error: package android.support.v4.content does not exist
import android.support.v4.content.ContextCompat;
                                 ^
C:\flutter\.pub-cache\hosted\pub.dartlang.org\simple_permissions-0.1.9\android\src\main\java\com\ethras\simplepermissions\SimplePermissionsPlugin.java:156: error: cannot find symbol
        ActivityCompat.requestPermissions(activity, perm, 0);
        ^
  symbol:   variable ActivityCompat
  location: class SimplePermissionsPlugin
C:\flutter\.pub-cache\hosted\pub.dartlang.org\simple_permissions-0.1.9\android\src\main\java\com\ethras\simplepermissions\SimplePermissionsPlugin.java:163: error: cannot find symbol
        return PackageManager.PERMISSION_GRANTED == ContextCompat.checkSelfPermission(activity, permission);
                                                    ^
  symbol:   variable ContextCompat
  location: class SimplePermissionsPlugin
C:\flutter\.pub-cache\hosted\pub.dartlang.org\simple_permissions-0.1.9\android\src\main\java\com\ethras\simplepermissions\SimplePermissionsPlugin.java:171: error: cannot find symbol
            if (ActivityCompat.shouldShowRequestPermissionRationale(registrar.activity(), permission)) {
                ^
  symbol:   variable ActivityCompat
  location: class SimplePermissionsPlugin
C:\flutter\.pub-cache\hosted\pub.dartlang.org\simple_permissions-0.1.9\android\src\main\java\com\ethras\simplepermissions\SimplePermissionsPlugin.java:175: error: cannot find symbol
                if (ActivityCompat.checkSelfPermission(registrar.context(), permission) == PackageManager.PERMISSION_GRANTED) {
                    ^
  symbol:   variable ActivityCompat
  location: class SimplePermissionsPlugin
6 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':simple_permissions:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
`

I guess it is from enabling AndroidX in the gradle.properties
`android.useAndroidX=true
android.enableJetifier=true`

so please consider fixing it.
thanks

**Comment by DarkSouL11** [comment]
Yes it is due to enabling AndroidX but is caused by one of the dependencies used by this package `simple_permissions`. I considered fixing for that plugin and creating a PR but couldn't find the repo for that plugin. So to fix this I will have to move to another flutter plugin for handling permissions. Before I fix this, if you have any recommended plugin for permission handling that would be helpful

**Comment by NewITCorp** [comment]
I forked from yours partially using permission_handler successfully, but not willing to publish. If you managed to fix it then I prefer to use yours.

**Comment by DarkSouL11** [comment]
Ok, I have already started work on it and will try to publish it today.

**Comment by DarkSouL11** [comment]
@NewITCorp I have published a new version of the plugin to pub with AndroidX support. Do check it out and confirm if it works. Reopen this issue if you face any trouble.
